#!/usr/bin/env node
// Generate the browser's side of the wire contract from `vibe-talk.schema.json`.
//
//   node contract/generate.mjs           rewrite web/contract.js and web/contract.d.ts
//   node contract/generate.mjs --check   exit 1, naming the stale files, instead of writing
//
// The schema itself is generated from the Rust types (`src/contract.rs`) by `tests/contract.rs`;
// `make -C vibe-talk contract` runs both steps in order. Nothing here is hand-maintained: edit
// the Rust types and regenerate.
//
// web/contract.js is Ajv's standalone validator code for every root in the schema, wrapped as a
// classic script that defines one global, `VibeTalkContract`. The page loads it before voice.js
// with no bundler and no module loader, so the generated code must not `require` anything; this
// script refuses to write output that does. web/contract.d.ts declares the same types for
// TypeScript's checkJs pass over voice.js, and is emitted by the small translator below, which
// fails loudly on any schema keyword it does not understand rather than approximating it.
//
// Output is deterministic for a given schema and a given locked Ajv version.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

let Ajv2020;
let standaloneCode;
try {
  Ajv2020 = require("ajv/dist/2020");
  standaloneCode = require("ajv/dist/standalone");
} catch {
  console.error(
    "contract/generate.mjs: the pinned generator dependencies are not installed.\n" +
      "  run: npm ci --prefix vibe-talk/contract",
  );
  process.exit(2);
}

const crate = join(here, "..");
const schemaPath = join(here, "vibe-talk.schema.json");
const outputs = {
  js: join(crate, "web", "contract.js"),
  dts: join(crate, "web", "contract.d.ts"),
};

const doc = JSON.parse(readFileSync(schemaPath, "utf8"));
const defs = doc.$defs;
const roots = doc.anyOf.map((root) => refName(root.$ref));

function refName(ref) {
  const prefix = "#/$defs/";
  if (typeof ref !== "string" || !ref.startsWith(prefix)) {
    throw new Error(`unsupported $ref ${JSON.stringify(ref)}`);
  }
  const name = ref.slice(prefix.length);
  if (!Object.hasOwn(defs, name)) throw new Error(`dangling $ref ${ref}`);
  return name;
}

const HEADER =
  "// GENERATED by contract/generate.mjs from contract/vibe-talk.schema.json. Do not edit;\n" +
  "// change src/contract.rs and run `make -C vibe-talk contract`.\n";

// ---------------------------------------------------------------------------------------------
// The tagged unions a receiver may meet a newer variant of.
//
// A `vibe-talk-v1` client ignores a frame `type` it does not know (a new server frame is backward
// compatible), so the page needs to tell "unknown tag" apart from "known tag, wrong shape". The
// tags come from the schema so they cannot drift from the Rust enum.

function unionTags(name) {
  const schema = defs[name];
  if (!Array.isArray(schema.oneOf)) throw new Error(`${name} is not a tagged union`);
  return schema.oneOf.map((variant) => {
    const tag = variant.properties?.type?.const;
    if (typeof tag !== "string") throw new Error(`${name} has a variant without a type tag`);
    return tag;
  });
}

const TAGGED = { VibeTalkV1ServerFrame: unionTags("VibeTalkV1ServerFrame") };

// ---------------------------------------------------------------------------------------------
// web/contract.js

function withoutDescriptions(value) {
  if (Array.isArray(value)) return value.map(withoutDescriptions);
  if (value === null || typeof value !== "object") return value;
  return Object.fromEntries(
    Object.entries(value)
      .filter(([key]) => key !== "description" && key !== "title")
      .map(([key, inner]) => [key, key === "properties" || key === "$defs"
        ? Object.fromEntries(Object.entries(inner).map(([k, v]) => [k, withoutDescriptions(v)]))
        : withoutDescriptions(inner)]),
  );
}

function generateValidators() {
  const ajv = new Ajv2020({
    code: { source: true, lines: true },
    // The schema carries `format: uint64` and friends as documentation for other generators; the
    // `minimum` beside each already says what the browser can check.
    validateFormats: false,
    allowUnionTypes: true,
    strict: true,
  });
  // Descriptions are for people and the declarations; the validators never read them, and Ajv
  // would otherwise embed every one in the page.
  ajv.addSchema(withoutDescriptions(doc));
  // An extensible union is compiled as one validator per variant instead of one for the whole
  // oneOf. Its tags are distinct constants, so "the variant its tag names accepts it" is exactly
  // the oneOf, and a malformed known frame is then described against that variant rather than
  // against whichever variant Ajv tried first. It also emits each variant's code once.
  const exports = {};
  for (const name of roots) {
    if (Object.hasOwn(TAGGED, name)) {
      TAGGED[name].forEach((tag, index) => {
        exports[`${name}/${tag}`] = `${doc.$id}#/$defs/${name}/oneOf/${index}`;
      });
    } else {
      exports[name] = `${doc.$id}#/$defs/${name}`;
    }
  }
  const code = standaloneCode(ajv, exports);
  if (/\brequire\(/.test(code)) {
    throw new Error(
      "Ajv's standalone output needs a runtime helper (it calls require()), which a classic " +
        "browser script cannot load. Avoid the schema feature that needs it, or vendor the helper.",
    );
  }
  return `${HEADER}//
// Runtime validators for the vibe-talk wire contract, and the one global the page uses them
// through: VibeTalkContract. See web/contract.d.ts for the types.
(function () {
"use strict";
const exports = {};
const module = { exports };
// ---- Ajv standalone output begins ----
${code.trim()}
// ---- Ajv standalone output ends ----
const variants = module.exports;
const roots = ${JSON.stringify(roots)};
const tagged = ${JSON.stringify(TAGGED)};

// The variant validator the value's tag selects, or null when it names none.
function variantFor(name, value) {
  const known = value !== null && typeof value === "object" && !Array.isArray(value) &&
    typeof value.type === "string" && tagged[name].includes(value.type);
  return known ? variants[name + "/" + value.type] : null;
}

function taggedValidator(name) {
  const check = function (value) {
    const variant = variantFor(name, value);
    if (variant === null) {
      check.errors = [{ instancePath: "/type", keyword: "enum",
        message: "must be one of " + tagged[name].map((tag) => JSON.stringify(tag)).join(", ") }];
      return false;
    }
    const valid = variant(value);
    check.errors = variant.errors;
    return valid;
  };
  return check;
}

const validators = {};
for (const name of roots) {
  validators[name] = Object.hasOwn(tagged, name) ? taggedValidator(name) : variants[name];
}

function describe(errors) {
  const first = errors && errors[0];
  if (!first) return "it does not match the contract";
  const where = first.instancePath || "the value";
  // A documented enum is a oneOf of constants, and Ajv reports each constant separately.
  if (first.keyword === "const") {
    const allowed = errors
      .filter((error) => error.keyword === "const" && error.instancePath === first.instancePath)
      .map((error) => JSON.stringify(error.params.allowedValue));
    return where + " must be one of " + allowed.join(", ");
  }
  return where + " " + first.message;
}

function validator(name) {
  if (!Object.prototype.hasOwnProperty.call(validators, name)) {
    throw new TypeError("no contract type named " + name);
  }
  return validators[name];
}

// Whether value is a well-formed name. Never throws for a known name.
function is(name, value) {
  return validator(name)(value) === true;
}

// value, if it is a well-formed name; otherwise an Error that says which part is wrong. The error
// carries contract = name so a caller can tell a contract violation from anything else.
function decode(name, value) {
  const check = validator(name);
  if (check(value)) return value;
  const error = new Error("malformed " + name + ": " + describe(check.errors));
  error.contract = name;
  throw error;
}

// For a tagged union a peer may extend: null when value is not an object or its type tag is one
// this contract does not know (the receiver ignores it), the value when it is well formed, and a
// thrown decode error when the tag is known but the shape is wrong.
function decodeTagged(name, value) {
  const tags = tagged[name];
  if (!tags) throw new TypeError(name + " is not an extensible tagged union");
  if (variantFor(name, value) === null) return null;
  return decode(name, value);
}

globalThis.VibeTalkContract = Object.freeze({ roots: Object.freeze(roots.slice()), is, decode, decodeTagged });
})();
`;
}

// ---------------------------------------------------------------------------------------------
// web/contract.d.ts

// Keywords that describe a value's shape, and those that only document or constrain it further
// in ways a static type cannot express (the runtime validator still enforces them).
const SHAPE = new Set(["type", "$ref", "properties", "required", "const", "oneOf", "anyOf", "items"]);
const ANNOTATION = new Set(["description", "default", "format", "minimum", "maximum", "title"]);

function checkKeywords(schema, where) {
  for (const key of Object.keys(schema)) {
    if (!SHAPE.has(key) && !ANNOTATION.has(key)) {
      throw new Error(`${where}: the declaration emitter does not understand schema keyword "${key}"`);
    }
  }
}

function doc_comment(text, indent) {
  if (!text) return "";
  const lines = text.replace(/\*\//g, "*\\/").split("\n");
  return `${indent}/**\n${lines.map((line) => `${indent} *${line ? ` ${line}` : ""}`).join("\n")}\n${indent} */\n`;
}

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function scalar(type, where) {
  switch (type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    default:
      throw new Error(`${where}: unsupported type "${type}" without a shape`);
  }
}

function union(members) {
  return [...new Set(members)].join(" | ");
}

// The TypeScript type of schema. `indent` is the indentation of the line the type starts on.
function tsType(schema, where, indent) {
  checkKeywords(schema, where);
  if (schema.$ref) return refName(schema.$ref);
  if (Object.hasOwn(schema, "const")) return JSON.stringify(schema.const);
  if (schema.oneOf) return union(schema.oneOf.map((s, i) => tsType(s, `${where}.oneOf[${i}]`, indent)));
  if (schema.anyOf) return union(schema.anyOf.map((s, i) => tsType(s, `${where}.anyOf[${i}]`, indent)));
  const types = Array.isArray(schema.type) ? schema.type : [schema.type];
  return union(
    types.map((type) => {
      if (type === "object") return objectType(schema, where, indent);
      if (type === "array") {
        if (!schema.items) throw new Error(`${where}: an array without items`);
        const item = tsType(schema.items, `${where}.items`, indent);
        return /[ |]/.test(item) ? `Array<${item}>` : `${item}[]`;
      }
      return scalar(type, where);
    }),
  );
}

function objectType(schema, where, indent) {
  const properties = schema.properties;
  if (!properties) throw new Error(`${where}: an object without properties`);
  const required = new Set(schema.required ?? []);
  const inner = `${indent}  `;
  const fields = Object.keys(properties).map((name) => {
    const property = properties[name];
    const key = IDENT.test(name) ? name : JSON.stringify(name);
    const optional = required.has(name) ? "" : "?";
    return `${doc_comment(property.description, inner)}${inner}${key}${optional}: ${tsType(property, `${where}.${name}`, inner)};`;
  });
  return `{\n${fields.join("\n")}\n${indent}}`;
}

function generateDeclarations() {
  const body = Object.keys(defs)
    .sort()
    .map((name) => {
      const schema = defs[name];
      const comment = doc_comment(schema.description, "  ");
      const isPlainObject = schema.type === "object" && !schema.oneOf && !schema.anyOf;
      if (isPlainObject) {
        return `${comment}  interface ${name} ${objectType(schema, name, "  ")}`;
      }
      return `${comment}  type ${name} = ${tsType(schema, name, "  ")};`;
    });
  const contract = roots.map((name) => `    ${name}: ${name};`).join("\n");
  const taggedNames = Object.keys(TAGGED).map((n) => JSON.stringify(n)).join(" | ");
  return `${HEADER}//
// The vibe-talk wire contract, for TypeScript's checkJs pass over the page. The same types are
// validated at runtime by web/contract.js.

declare namespace VibeTalk {
${body.join("\n\n")}

  /** Every type that crosses a boundary on its own, by name. */
  interface Contract {
${contract}
  }

  /** A contract type a peer may extend with new \`type\` tags. */
  type Tagged = ${taggedNames};

  /** The error {@link VibeTalkContract.decode} throws. */
  interface ContractError extends Error {
    contract: keyof Contract;
  }
}

/** Runtime validators for {@link VibeTalk.Contract}, defined by web/contract.js. */
declare const VibeTalkContract: {
  /** Every root type name. */
  readonly roots: ReadonlyArray<keyof VibeTalk.Contract>;
  /** Whether value is a well-formed name. */
  is<K extends keyof VibeTalk.Contract>(name: K, value: unknown): value is VibeTalk.Contract[K];
  /** value, if well formed; otherwise throws a {@link VibeTalk.ContractError}. */
  decode<K extends keyof VibeTalk.Contract>(name: K, value: unknown): VibeTalk.Contract[K];
  /**
   * null when value carries a \`type\` tag this contract does not know, which a receiver ignores;
   * otherwise as {@link decode}.
   */
  decodeTagged<K extends VibeTalk.Tagged>(name: K, value: unknown): VibeTalk.Contract[K] | null;
};
`;
}

// ---------------------------------------------------------------------------------------------

const generated = {
  [outputs.js]: generateValidators(),
  [outputs.dts]: generateDeclarations(),
};

const check = process.argv.includes("--check");
const stale = [];
for (const [path, text] of Object.entries(generated)) {
  let current = null;
  try {
    current = readFileSync(path, "utf8");
  } catch {
    current = null;
  }
  if (current === text) continue;
  if (check) {
    stale.push(relative(crate, path));
  } else {
    writeFileSync(path, text);
    console.log(`wrote ${relative(crate, path)}`);
  }
}
if (stale.length > 0) {
  console.error(
    `stale generated contract files: ${stale.join(", ")}\n` +
      "  the schema changed without regenerating them. Run `make -C vibe-talk contract` and commit the result.",
  );
  process.exit(1);
}
