"""Record whole-run and per-step performance measurements.

The file-backed sink maintains stable CSV schemas, preserves dynamically observed
measurement columns, and surfaces directory or write failures instead of dropping data
silently. Linux cgroup measurements are optional and remain blank when unavailable.
"""

from __future__ import annotations

import csv
import fcntl
import os
import re
import resource
import sys
import time
from contextlib import contextmanager
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Iterator

from dagrun.protocols import MetricsSink, RunWindow

__all__ = [
    "CSV_COLUMNS",
    "STEP_PROFILE_COLUMNS",
    "STEP_TIMESERIES_COLUMNS",
    "ENRICHMENT_COLUMNS",
    "CENSORING_COLUMNS",
    "new_run_id",
    "machine_id",
    "nproc",
    "container_class",
    "store_paths",
    "append_step_profiles",
    "append_step_timeseries",
    "PerfWindow",
    "CsvMetricsSink",
    "effective_cpu_quota",
]

#: CSV row terminator. The stdlib csv module defaults to RFC-4180 ``\r\n`` (CRLF); we pin ``\n``
#: (LF) so the on-disk store is byte-identical to the Rust build (which writes LF) and a checked-in
#: store does not churn every line when regenerated by the other build.
_CSV_LINETERMINATOR = "\n"

# Canonical decimal spellings shared with the Rust writer. Readers remain tolerant of older
# Python rows that used variable-width decimal text and title-case booleans.
_WHOLE_RUN_DECIMALS = {
    "wall_s": 1,
    "user_s": 1,
    "sys_s": 1,
    "pct_we": 2,
    "pct_other": 2,
    "total_busy_pct": 2,
}
_STEP_PROFILE_DECIMALS = {
    "elapsed_s": 3,
    "started_offset_s": 3,
    "finished_offset_s": 3,
    "effective_cores": 4,
    "user_s": 3,
    "sys_s": 3,
    "throttled_s": 3,
    "quota_utilization_pct": 2,
    "external_cpu_s": 3,
    "external_cores": 3,
    "load1_start": 3,
    "load1_end": 3,
    "load5_start": 3,
    "load5_end": 3,
    "host_cpu_psi_avg10_start": 2,
    "host_cpu_psi_avg10_end": 2,
    "host_cpu_psi_avg60_start": 2,
    "host_cpu_psi_avg60_end": 2,
    "host_memory_psi_avg10_start": 2,
    "host_memory_psi_avg10_end": 2,
    "host_memory_psi_avg60_start": 2,
    "host_memory_psi_avg60_end": 2,
    "host_io_psi_avg10_start": 2,
    "host_io_psi_avg10_end": 2,
    "host_io_psi_avg60_start": 2,
    "host_io_psi_avg60_end": 2,
    "step_cpu_psi_avg10_start": 2,
    "step_cpu_psi_avg10_end": 2,
    "step_cpu_psi_avg60_start": 2,
    "step_cpu_psi_avg60_end": 2,
}

# ---------------------------------------------------------------------------
# On-disk schemas. Append-only: never reorder or remove a column (old rows would
# misalign); only append new columns at the end.
# ---------------------------------------------------------------------------

#: Whole-run summary columns, one row per run.
CSV_COLUMNS = [
    "timestamp",       # RFC-3339 UTC time the run finished (seconds, trailing Z)
    "machine_id",      # CPU model, run-benchmark-style (spaces->_, non-alnum stripped)
    "git_sha",         # source revision at run time
    "nproc",           # cores the run could use (len(sched_getaffinity))
    "wall_s",          # wall-clock seconds of the run window
    "user_s",          # delta RUSAGE_CHILDREN user CPU-seconds
    "sys_s",           # delta RUSAGE_CHILDREN system CPU-seconds
    "result",          # run outcome verbatim (e.g. "pass" | "fail")
    "n_steps",         # number of steps run
    "pct_we",          # our (user+sys) CPU / (nproc*wall)
    "pct_other",       # other-activity CPU / (nproc*wall)
    "total_busy_pct",  # total system busy CPU / (nproc*wall)
    "ipc",             # optional instructions-per-cycle (blank when unavailable)
    "cache_miss_pct",  # optional cache-miss rate % (blank when unavailable)
    "jobs",            # active-step ceiling (existing schema name; CLI --max-steps / -s)
]

#: Standard per-step profile columns, keyed by ``machine_id`` + ``container_class``. These
#: match exactly what the scheduler emits: the run context stamped by
#: :func:`append_step_profiles`, followed by the per-step measurement keys the scheduler
#: builds in ``scheduler._run_step`` (its ``row`` dict). Dynamic ``cpu.*`` counters vary by
#: cgroup manager and are appended per run AFTER these standard columns (see
#: :func:`_step_profile_fieldnames`), so they are captured without being hard-coded here.
#: Rich parallel-speedup enrichment columns, appended to STEP_PROFILE_COLUMNS. Captured UNDER
#: cgroup boxing on Linux and left BLANK when unavailable (an un-boxed run / missing /proc file),
#: exactly like the originating writer. The NAMES mirror the originating ``validate_perflog``
#: STEP_PROFILE_COLUMNS so a later schema unification is a rename, not a redesign. Produced by
#: :func:`dagrun.profile_enrich.step_enrichment_columns`.
ENRICHMENT_COLUMNS = [
    "effective_cores",         # child CPU-seconds / wall (cpu.stat usage_usec / elapsed_s)
    "user_s",                  # cpu.stat user_usec, seconds
    "sys_s",                   # cpu.stat system_usec, seconds
    "throttled_s",             # cpu.stat throttled_usec, seconds
    "quota_utilization_pct",   # effective_cores / applied inner -j cap, percent
    "external_cpu_s",          # host CPU burned by OTHER tenants during the window, seconds
    "external_cores",          # ...expressed as cores
    "co_tenants_start", "co_tenants_end",
    "ambient_bucket",          # quiet | moderate | busy
    "load1_start", "load1_end", "load5_start", "load5_end",
    "host_cpu_psi_avg10_start", "host_cpu_psi_avg10_end",
    "host_cpu_psi_avg60_start", "host_cpu_psi_avg60_end",
    "host_memory_psi_avg10_start", "host_memory_psi_avg10_end",
    "host_memory_psi_avg60_start", "host_memory_psi_avg60_end",
    "host_io_psi_avg10_start", "host_io_psi_avg10_end",
    "host_io_psi_avg60_start", "host_io_psi_avg60_end",
    "step_cpu_psi_avg10_start", "step_cpu_psi_avg10_end",
    "step_cpu_psi_avg60_start", "step_cpu_psi_avg60_end",
]

#: Provenance a later reader needs to tell a TRUE peak from a CENSORED one, and to know which
#: rows ran at the same time. Appended after the enrichment block (append-only: never reorder).
#:
#: ``peak_bytes`` on its own does not say what it measured. A step whose peak equals the
#: ``memory.max`` that was applied to it used everything it was allowed and may have wanted more;
#: treating that number as an observed maximum under-estimates the workload permanently, and
#: nothing in the row as it stood could detect the case. These columns make it detectable:
#:
#: * ``run_id`` groups the rows of exactly ONE DAG execution. Two concurrent runs on one machine
#:   share ``machine_id``, ``container_class``, ``git_sha`` and often ``outer_jobs``, and
#:   ``timestamp`` is stamped once per BATCH, so without this there is no key that separates them.
#: * ``started_offset_s`` / ``finished_offset_s`` are seconds from that run's own origin, so the
#:   overlap between any two steps of a run is a comparison of two intervals. Wall-clock
#:   timestamps cannot do this: the batch carries one.
#: * ``memory_max_bytes`` is the TIGHTEST cap the KERNEL held over the step across every level
#:   the runner can see — its own cgroup and the delegated scope, because cgroup-v2 limits are
#:   hierarchical and a step given no inner cap is still held by the scope's ceiling. A decimal
#:   byte count, the literal ``max`` when no such level bounds it, or BLANK when the cap is
#:   unknown. Blank and ``max`` are different answers and must not be merged: unknown cannot
#:   rule out censoring, while ``max`` rules out censoring BY THE RUNNER'S OWN CAPS. It does not
#:   rule out an ancestor above the delegated scope (a container memory limit, a user slice),
#:   which the runner cannot see.
#: * ``memory_events_*`` are the step cgroup's ``memory.events`` counters. They need no
#:   subtraction to be deltas — the cgroup is created for the step and destroyed after it.
#:   ``memory_events_max > 0`` with ``memory_events_oom_kill == 0`` is the reclaim-at-cap case: a
#:   step that PASSED while pinned to its ceiling, which is precisely the sample a naive reader
#:   would mistake for a comfortable fit. They are the STEP cgroup's own counters, and the kernel
#:   does not charge an ancestor's limit events to a descendant, so ``memory_events_max == 0`` is
#:   not by itself proof that nothing clamped the step.
CENSORING_COLUMNS = [
    "run_id",
    "started_offset_s",
    "finished_offset_s",
    "memory_max_bytes",
    "memory_events_low",
    "memory_events_high",
    "memory_events_max",
    "memory_events_oom",
    "memory_events_oom_kill",
]

STEP_PROFILE_COLUMNS = [
    # Run context, stamped onto every row by append_step_profiles().
    "timestamp", "machine_id", "container_class", "git_sha", "outer_jobs",
    "profile_base_sha", "enforcement_kind", "runner_name",
    # Per-step measurements produced by the scheduler.
    "step", "classification", "inner_jobs", "elapsed_s", "returncode", "ok",
    "timed_out", "cpu_timed_out", "oom_kills", "peak_bytes", "thread_peak",
    # Rich parallel-speedup enrichment (appended; blank when unavailable).
    *ENRICHMENT_COLUMNS,
    # Run-overlap and applied-cap provenance (appended; blank when unavailable).
    *CENSORING_COLUMNS,
]

#: Fixed prefix for the opt-in interval-level trace. The first nine fields are the same run
#: context used by the aggregate profile store. Sweep provenance, when present, is appended as a
#: sorted dynamic tail so Python and Rust can write the same schema without teaching the sampler
#: about sweep policy.
STEP_TIMESERIES_COLUMNS = [
    "timestamp",
    "machine_id",
    "container_class",
    "git_sha",
    "outer_jobs",
    "profile_base_sha",
    "enforcement_kind",
    "runner_name",
    "run_id",
    "step",
    "inner_jobs",
    "sample_index",
    "sample_kind",
    "elapsed_s",
    "interval_s",
    "cpu_usage_s",
    "user_s",
    "sys_s",
    "effective_cores",
    "user_cores",
    "system_cores",
    "throttled_s",
    "interval_throttled_s",
    "thread_count",
]


# ---------------------------------------------------------------------------
# Machine / container identity + system-wide CPU sampling.
# ---------------------------------------------------------------------------


def machine_id() -> str:
    """Per-machine identifier from ``/proc/cpuinfo`` 'model name' (spaces -> underscores,
    then non ``[A-Za-z0-9_-]`` stripped). Falls back to the hostname, then ``"unknown"``.
    Mirrors run_benchmark-style CPU naming so rows group cleanly per machine."""
    try:
        with open("/proc/cpuinfo") as f:
            for line in f:
                if line.startswith("model name"):
                    name = line.split(":", 1)[1].strip().replace(" ", "_")
                    return re.sub(r"[^A-Za-z0-9_-]", "", name)
    except OSError:
        pass
    return re.sub(r"[^A-Za-z0-9_-]", "", os.uname().nodename) or "unknown"


def new_run_id() -> str:
    """A fresh identifier for ONE DAG execution: nanoseconds since the epoch and the runner
    PID, both hex, concatenated.

    Uniqueness comes from the pair, not from either half. Two runs on one host cannot share
    a start nanosecond, and a PID reused after a clock step cannot collide with the earlier
    run that held it. The value is opaque: a reader groups rows by equality and never parses
    it, so nothing depends on how it was built."""
    return f"{time.time_ns():016x}{os.getpid():08x}"


def nproc() -> int:
    """Cores this run could actually use (respects CPU affinity / cgroup pin)."""
    try:
        return len(os.sched_getaffinity(0))
    except (AttributeError, OSError):
        return os.cpu_count() or 1


def _own_cgroup_relpath() -> str | None:
    """This process's cgroup-v2 path relative to the mount root, e.g. ``/user.slice/foo.scope``."""
    try:
        with open("/proc/self/cgroup") as f:
            for line in f:
                # cgroup-v2 unified line: "0::/user.slice/..."
                if line.startswith("0::"):
                    return line.split("::", 1)[1].strip() or "/"
    except OSError:
        pass
    return None


def effective_cpu_quota(
    *, mount_root: str | Path = "/sys/fs/cgroup", relpath: str | None = None
) -> str:
    """The CPU quota actually BINDING this process, as a normalized ``<quota>_<period>`` string.

    ``mount_root`` and ``relpath`` select the hierarchy to inspect; by default this process's
    own cgroup under the standard cgroup-v2 mount.

    Walks the selected cgroup and every ancestor up to the mount root and returns the most
    restrictive `cpu.max` (smallest quota/period ratio), because a cgroup-v2 quota is enforced by
    the whole ancestor chain, not just the leaf. Returns ``"max"`` when nothing in the chain
    constrains CPU, and ``"unknown"`` when the hierarchy cannot be read at all.

    The mount-root ``/sys/fs/cgroup/cpu.max`` must NOT be used for this: on an ordinary host that
    file does not exist, so the quota half of :func:`container_class` degenerates to the constant
    ``unknown`` and stops distinguishing anything. That matters because a slice several levels up
    is where a CPU bandwidth cap typically lives -- a step can run with a full-width affinity mask
    and still be held to a fraction of a core by an ancestor's quota. Two genuinely different
    containers then share one key, the speedup model fits a single curve across both populations,
    and it recommends the wide machine's width to the constrained one.
    """
    if relpath is None:
        relpath = _own_cgroup_relpath()
    if relpath is None:
        return "unknown"
    best_ratio: float | None = None
    best_text = "max"
    seen_any = False
    root = Path(mount_root)
    node = root / relpath.lstrip("/")
    while True:
        try:
            raw = (node / "cpu.max").read_text().strip()
            seen_any = True
            parts = raw.split()
            if len(parts) == 2 and parts[0] != "max":
                quota, period = int(parts[0]), int(parts[1])
                if period > 0:
                    ratio = quota / period
                    if best_ratio is None or ratio < best_ratio:
                        best_ratio, best_text = ratio, f"{quota}_{period}"
        except (OSError, ValueError):
            pass
        if node == root or root not in node.parents:
            break
        node = node.parent
    if not seen_any:
        return "unknown"
    return best_text


def container_class() -> str:
    """Stable CPU-container key: affinity width plus the CPU quota binding this process.

    Both halves matter and they constrain independently: a cpuset narrows WHICH cpus (reflected in
    ``nproc()`` via the affinity mask) while ``cpu.max`` caps total CPU BANDWIDTH. Samples taken
    under different containers must not share a key, or the speedup model fits one curve across
    incompatible populations."""
    return f"affinity{nproc()}_cpu-max-{effective_cpu_quota()}"


def _whole_run_csv_name(machine_id_value: str | None = None) -> str:
    """The whole-run summary CSV file name for a machine: ``<machine_id>.csv``."""
    mid = machine_id() if machine_id_value is None else machine_id_value
    return f"{mid}.csv"


def _step_profiles_csv_name() -> str:
    """The per-step profile CSV file name:
    ``step_profiles_<machine_id>_<container_class>.csv``."""
    return f"step_profiles_{machine_id()}_{container_class()}.csv"


def store_paths(output_dir: str | Path) -> list[Path]:
    """The profile-store file paths a single ``run``/``sweep`` writes into ``output_dir``: the
    whole-run summary (``<machine_id>.csv``) and the per-step profile CSV
    (``step_profiles_<machine_id>_<container_class>.csv``).

    The CLI reports EXACTLY these (filtered to files that exist) rather than globbing the whole
    store — a persistent store also holds prior runs' other-``container_class`` variants on the same
    machine, and globbing would over-report files this run never wrote."""
    base = Path(output_dir)
    return [base / _whole_run_csv_name(), base / _step_profiles_csv_name()]


def _proc_stat_busy_jiffies() -> int | None:
    """Sum of all non-idle jiffies from the aggregate 'cpu ' line of ``/proc/stat``.
    Busy = everything except idle + iowait (iowait is not CPU-burning work). ``None`` when
    ``/proc/stat`` is unreadable or malformed."""
    try:
        with open("/proc/stat") as f:
            first = f.readline()
    except OSError:
        return None
    parts = first.split()
    if not parts or parts[0] != "cpu":
        return None
    vals = [int(x) for x in parts[1:]]
    idle = vals[3] if len(vals) > 3 else 0      # idle jiffies
    iowait = vals[4] if len(vals) > 4 else 0    # iowait jiffies (when present)
    return sum(vals) - idle - iowait


# ---------------------------------------------------------------------------
# CSV append helpers (self-migrating schemas).
# ---------------------------------------------------------------------------


def _timestamp() -> str:
    """Canonical UTC timestamp shared with the Rust writer."""

    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def _wire_row(
    row: Mapping[str, object], decimal_places: Mapping[str, int] | None = None
) -> dict[str, str]:
    """Encode an in-memory row using the shared Python/Rust CSV scalar spellings."""

    decimals = decimal_places or {}
    encoded: dict[str, str] = {}
    for key, value in row.items():
        if value is None:
            encoded[key] = ""
        elif isinstance(value, bool):
            encoded[key] = "true" if value else "false"
        elif isinstance(value, float) and key in decimals:
            encoded[key] = f"{value:.{decimals[key]}f}"
        else:
            encoded[key] = str(value)
    return encoded


@contextmanager
def _profile_file_lock(csv_path: Path) -> Iterator[None]:
    """Take the persistent advisory lock shared by Python and Rust profile writers.

    The stable inode matters: unlinking a held lock file allows a racing process to create and
    lock a different inode while the first writer is still active. Hidden ``.locks`` directories
    keep these coordination files separate from profiling artifacts.
    """

    lock_dir = csv_path.parent / ".locks"
    lock_dir.mkdir(parents=True, exist_ok=True)
    lock_path = lock_dir / f"{csv_path.name}.lock"
    with open(lock_path, "a+b") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(lock, fcntl.LOCK_UN)


def _ensure_dir(output_dir: str | Path) -> Path | None:
    """Create ``output_dir`` on demand and return it, or warn + return ``None`` on failure.

    Unlike the originating implementation (which required a pre-existing opt-in directory
    two levels up from the checkout), the directory is explicit and created eagerly; an
    inability to create it is a visible warning, never a silent skip."""
    path = Path(output_dir)
    try:
        path.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        sys.stderr.write(f"[perflog] skipped: cannot create output dir {path} ({exc})\n")
        return None
    return path


def append_step_profiles(
    output_dir: str | Path,
    rows: Sequence[Mapping[str, object]],
    *,
    git_sha: str,
    outer_jobs: int,
    profile_base_sha: str | None = None,
    enforcement_kind: str = "unverified",
    runner_name: str = "local",
    run_id: str | None = None,
) -> Path | None:
    """Append per-step measurement ``rows`` to a machine/container-specific CSV.

    The file is ``<output_dir>/step_profiles_<machine_id>_<container_class>.csv``. Each row
    is a heterogeneous column->value mapping owned by the caller (the scheduler's per-step
    ``row``); the shared run context (timestamp, machine id, container class, git SHA, outer
    job count, and the provenance columns) is stamped onto every row here. Writes are
    serialized with the persistent ``flock`` sidecar protocol used by the on-disk format, so
    concurrent compatible writers cannot interleave.

    The header is derived from the ACTUAL row keys: the standard columns
    (:data:`STEP_PROFILE_COLUMNS`) come first, then any extra per-row keys (dynamic ``cpu.*``
    counters) are appended in sorted order, so no real data is ever dropped. If an
    existing file has a narrower header it is widened in place (older rows keep their columns)
    before appending. The file is created on first write. Returns the CSV path, or ``None``
    if the output directory could not be created (a visible warning is emitted).

    ``profile_base_sha`` defaults to ``git_sha``. ``enforcement_kind`` and ``runner_name``
    are recorded verbatim. ``run_id`` identifies the one DAG execution these rows came from
    and defaults to a fresh :func:`new_run_id`; pass the run's own id so every batch of a
    single execution carries the same value, because that column is the ONLY thing that
    separates two concurrent runs sharing this machine, container class and commit."""
    logs_dir = _ensure_dir(output_dir)
    if logs_dir is None:
        return None
    path = logs_dir / _step_profiles_csv_name()
    common: dict[str, object] = {
        "timestamp": _timestamp(),
        "machine_id": machine_id(),
        "container_class": container_class(),
        "git_sha": git_sha,
        "outer_jobs": outer_jobs,
        "profile_base_sha": git_sha if profile_base_sha is None else profile_base_sha,
        "enforcement_kind": enforcement_kind,
        "runner_name": runner_name,
        "run_id": new_run_id() if run_id is None else run_id,
    }
    full_rows = [
        _wire_row({**common, **row}, _STEP_PROFILE_DECIMALS) for row in rows
    ]
    fieldnames = _step_profile_fieldnames(full_rows)
    with _profile_file_lock(path):
        _append_rows_merging_header(path, full_rows, fieldnames)
    return path


def append_step_timeseries(
    output_dir: str | Path,
    rows: Sequence[Mapping[str, object]],
    *,
    git_sha: str,
    outer_jobs: int,
    profile_base_sha: str | None = None,
    enforcement_kind: str = "unverified",
    runner_name: str = "local",
    run_id: str,
) -> Path | None:
    """Append one run's interval-level step samples to ``traces/<run_id>.csv``.

    Time-series rows deliberately live outside the aggregate profile CSV: they are high-volume
    observations within a trial, not independent trials for the scaling estimator. The run id is
    also stamped into every row and sanitized only for the filename, so a caller-supplied id can
    never escape the trace directory. Dynamic fields (notably sweep provenance) follow the fixed
    schema in sorted order.
    """
    if not rows:
        return None
    logs_dir = _ensure_dir(Path(output_dir) / "traces")
    if logs_dir is None:
        return None
    safe_run_id = re.sub(r"[^A-Za-z0-9_.-]", "_", run_id) or "unknown"
    path = logs_dir / f"{safe_run_id}.csv"
    common: dict[str, object] = {
        "timestamp": _timestamp(),
        "machine_id": machine_id(),
        "container_class": container_class(),
        "git_sha": git_sha,
        "outer_jobs": outer_jobs,
        "profile_base_sha": git_sha if profile_base_sha is None else profile_base_sha,
        "enforcement_kind": enforcement_kind,
        "runner_name": runner_name,
        "run_id": run_id,
    }
    full_rows = [_wire_row({**common, **row}) for row in rows]
    fieldnames = list(STEP_TIMESERIES_COLUMNS)
    standard = set(fieldnames)
    fieldnames.extend(sorted({key for row in full_rows for key in row if key not in standard}))
    with _profile_file_lock(path):
        _append_rows_merging_header(path, full_rows, fieldnames)
    return path


def _step_profile_fieldnames(rows: Sequence[Mapping[str, object]]) -> list[str]:
    """Per-step CSV column order: the standard columns (:data:`STEP_PROFILE_COLUMNS`) first, then
    any extra per-row keys (dynamic ``cpu.*`` counters) SORTED ALPHABETICALLY. Both builds sort
    this dynamic tail identically (the Rust build iterates a ``BTreeSet``), so the CSV header is
    byte-identical across languages — asserted by the cross/ differential. Always captures the
    standard keys and never drops real row data (No Silent Failure)."""
    fields = list(STEP_PROFILE_COLUMNS)
    standard = set(fields)
    extra: set[str] = set()
    for row in rows:
        for key in row:
            if key not in standard:
                extra.add(key)
    fields.extend(sorted(extra))
    return fields


def _append_rows_merging_header(
    csv_path: Path, rows: Sequence[Mapping[str, object]], fieldnames: Sequence[str]
) -> None:
    """Append ``rows`` to ``csv_path`` under a header that is the union of any pre-existing
    header and ``fieldnames`` (existing columns first, then new columns appended).

    Creates the file with ``fieldnames`` when it is absent or empty; when an existing header
    is narrower, the file is rewritten to the widened header first so older rows keep their
    columns and no column is ever dropped. Each row is projected onto the final header, so an
    extra key that somehow escaped ``fieldnames`` is stored under a column (never a raise) as
    long as it is in the header. The caller holds any needed lock.

    This is the single place first-write file creation is handled: the file is opened for
    reading ONLY when it already exists, so a brand-new CSV is created cleanly instead of
    raising ``FileNotFoundError``."""
    new = not csv_path.exists() or csv_path.stat().st_size == 0
    if new:
        header = list(fieldnames)
    else:
        with open(csv_path, newline="", encoding="utf-8") as existing:
            reader = csv.DictReader(existing)
            header = list(reader.fieldnames or [])
            old_rows = list(reader)
        widened = list(header)
        for col in fieldnames:
            if col not in widened:
                widened.append(col)
        if widened != header:
            tmp = csv_path.with_suffix(csv_path.suffix + ".tmp")
            with open(tmp, "w", newline="", encoding="utf-8") as out:
                writer = csv.DictWriter(out, fieldnames=widened, lineterminator=_CSV_LINETERMINATOR)
                writer.writeheader()
                for old_row in old_rows:
                    old_row.pop(None, None)  # drop csv restkey overflow
                    writer.writerow({col: old_row.get(col, "") for col in widened})
            os.replace(tmp, csv_path)
            header = widened
    with open(csv_path, "a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=header, lineterminator=_CSV_LINETERMINATOR)
        if new:
            writer.writeheader()
        for row in rows:
            writer.writerow({col: row.get(col, "") for col in header})


def _append_whole_run_row(csv_path: Path, row: Mapping[str, object]) -> None:
    """Append one whole-run summary ``row`` to ``csv_path`` under the additive
    :data:`CSV_COLUMNS` schema, merging with any pre-existing (possibly wider) header so
    older files keep their extra columns intact. The file is created on first write."""
    with _profile_file_lock(csv_path):
        _append_rows_merging_header(
            csv_path, [_wire_row(row, _WHOLE_RUN_DECIMALS)], CSV_COLUMNS
        )


# ---------------------------------------------------------------------------
# Whole-run window.
# ---------------------------------------------------------------------------


class PerfWindow:
    """A started whole-run measurement bracket; :meth:`finish` appends one summary row.

    Concrete implementation of :class:`~dagrun.protocols.RunWindow`. Construct
    via :meth:`start` (captures baseline wall clock, ``RUSAGE_CHILDREN`` CPU, and
    system-wide busy jiffies), then call :meth:`finish` once the DAG completes. The row is
    written to ``<output_dir>/<machine_id>.csv``. The summary row is appended regardless of
    ``result`` (both passing and failing runs are recorded)."""

    def __init__(
        self,
        *,
        output_dir: str | Path,
        git_sha: str,
        machine_id_value: str,
        wall_start: float,
        ru_start: resource.struct_rusage,
        busy_start: int | None,
        ipc: object = "",
        cache_miss_pct: object = "",
    ) -> None:
        self.output_dir = output_dir
        self.git_sha = git_sha
        self.machine_id_value = machine_id_value
        self.wall_start = wall_start
        self.ru_start = ru_start
        self.busy_start = busy_start
        self.ipc = ipc
        self.cache_miss_pct = cache_miss_pct

    @classmethod
    def start(
        cls,
        *,
        output_dir: str | Path,
        git_sha: str,
        machine_id_value: str | None = None,
        ipc: object = "",
        cache_miss_pct: object = "",
    ) -> "PerfWindow":
        """Open the window, capturing baseline counters at the current instant."""
        return cls(
            output_dir=output_dir,
            git_sha=git_sha,
            machine_id_value=machine_id() if machine_id_value is None else machine_id_value,
            wall_start=time.time(),
            ru_start=resource.getrusage(resource.RUSAGE_CHILDREN),
            busy_start=_proc_stat_busy_jiffies(),
            ipc=ipc,
            cache_miss_pct=cache_miss_pct,
        )

    def finish(self, *, result: str, n_steps: int, jobs: int) -> Mapping[str, object] | None:
        """Compute window metrics and append the summary row.

        Derives the contention split from the baseline captured at :meth:`start`:

        * ``pct_we``          = our (user+sys child CPU-seconds) / (nproc * wall)
        * ``pct_other``       = (system busy CPU-seconds - our CPU-seconds) / (nproc * wall)
        * ``total_busy_pct``  = system busy CPU-seconds / (nproc * wall)

        ``pct_other`` / ``total_busy_pct`` are blank when ``/proc/stat`` could not be
        sampled at both ends. Returns the recorded row for logging, or ``None`` when the
        output directory could not be created / written (a visible warning is emitted).
        Never raises into the run path — metrics recording must not fail a run."""
        try:
            wall = max(time.time() - self.wall_start, 0.0)
            ru_end = resource.getrusage(resource.RUSAGE_CHILDREN)
            user_s = max(ru_end.ru_utime - self.ru_start.ru_utime, 0.0)
            sys_s = max(ru_end.ru_stime - self.ru_start.ru_stime, 0.0)
            ncpu = nproc()
            capacity = ncpu * wall if wall > 0 else 0.0
            our_cpu = user_s + sys_s

            total_busy_s: float | None = None
            busy_end = _proc_stat_busy_jiffies()
            if self.busy_start is not None and busy_end is not None:
                clk = os.sysconf("SC_CLK_TCK") or 100
                total_busy_s = max(busy_end - self.busy_start, 0) / clk

            def pct(x: float) -> float | str:
                return round(100.0 * x / capacity, 2) if capacity > 0 else ""

            pct_we = pct(our_cpu)
            if total_busy_s is not None:
                pct_other: float | str = pct(max(total_busy_s - our_cpu, 0.0))
                total_busy_pct: float | str = pct(total_busy_s)
            else:
                pct_other = ""
                total_busy_pct = ""

            row: dict[str, object] = {
                "timestamp": _timestamp(),
                "machine_id": self.machine_id_value,
                "git_sha": self.git_sha,
                "nproc": ncpu,
                "wall_s": round(wall, 1),
                "user_s": round(user_s, 1),
                "sys_s": round(sys_s, 1),
                "result": result,
                "n_steps": n_steps,
                "pct_we": pct_we,
                "pct_other": pct_other,
                "total_busy_pct": total_busy_pct,
                "ipc": self.ipc,
                "cache_miss_pct": self.cache_miss_pct,
                "jobs": jobs,
            }

            logs_dir = _ensure_dir(self.output_dir)
            if logs_dir is None:
                return None
            _append_whole_run_row(logs_dir / _whole_run_csv_name(self.machine_id_value), row)
            return row
        except Exception as exc:  # never break the run over perf logging
            try:
                sys.stderr.write(f"[perflog] whole-run row skipped ({exc})\n")
            except Exception:
                pass
            return None


# ---------------------------------------------------------------------------
# Concrete MetricsSink.
# ---------------------------------------------------------------------------


class CsvMetricsSink(MetricsSink):
    """File-backed :class:`~dagrun.protocols.MetricsSink` writing CSV rows.

    Carries the fixed run context (explicit output directory, git SHA, machine id, and the
    per-step provenance columns) as construction state; the scheduler passes only the
    varying per-call data. The explicit output directory is created on demand."""

    def __init__(
        self,
        output_dir: str | Path,
        *,
        git_sha: str,
        machine_id_value: str | None = None,
        profile_base_sha: str | None = None,
        enforcement_kind: str = "unverified",
        runner_name: str = "local",
        ipc: object = "",
        cache_miss_pct: object = "",
        run_id: str | None = None,
    ) -> None:
        self.output_dir = output_dir
        self.git_sha = git_sha
        self.machine_id_value = machine_id() if machine_id_value is None else machine_id_value
        self.profile_base_sha = profile_base_sha
        self.enforcement_kind = enforcement_kind
        self.runner_name = runner_name
        self.ipc = ipc
        self.cache_miss_pct = cache_miss_pct
        #: Identifies the ONE DAG execution this sink records. Minted here, at sink
        #: construction, rather than per batch: a run that records its rows in more than one
        #: call must still be one group, and a sink that re-minted per call would silently
        #: split it.
        self.run_id = new_run_id() if run_id is None else run_id

    def start_run_window(self) -> RunWindow:
        """Open the whole-run window bound to this sink's context."""
        return PerfWindow.start(
            output_dir=self.output_dir,
            git_sha=self.git_sha,
            machine_id_value=self.machine_id_value,
            ipc=self.ipc,
            cache_miss_pct=self.cache_miss_pct,
        )

    def record_step_profiles(
        self, rows: Sequence[Mapping[str, object]], *, jobs: int
    ) -> str | None:
        """Append per-step profile ``rows`` (accumulated during the run) to durable storage.

        Delegates to :func:`append_step_profiles`; ``jobs`` is the active-step ceiling and is
        stamped as the existing ``outer_jobs`` field on every row. Rows are recorded regardless
        of run outcome. Returns the CSV path as a string, or ``None`` when recording was skipped
        (a visible warning is emitted)."""
        path = append_step_profiles(
            self.output_dir,
            rows,
            git_sha=self.git_sha,
            outer_jobs=jobs,
            profile_base_sha=self.profile_base_sha,
            enforcement_kind=self.enforcement_kind,
            runner_name=self.runner_name,
            run_id=self.run_id,
        )
        return None if path is None else str(path)

    def record_step_timeseries(
        self, rows: Sequence[Mapping[str, object]], *, jobs: int
    ) -> str | None:
        """Persist opt-in interval samples in this execution's dedicated trace CSV."""
        path = append_step_timeseries(
            self.output_dir,
            rows,
            git_sha=self.git_sha,
            outer_jobs=jobs,
            profile_base_sha=self.profile_base_sha,
            enforcement_kind=self.enforcement_kind,
            runner_name=self.runner_name,
            run_id=self.run_id,
        )
        return None if path is None else str(path)
