"""Always-on perf logging for a DAG run: whole-run window + per-step profile CSVs.

Ported from DeepScry's ``scripts/validate_perflog.py`` (ds-1190), stripped of every
DeepScry/MTG specific. The generic contract:

* :class:`PerfWindow` brackets the whole run and appends ONE row recording how long the
  run took and *who* was using the CPU during the window. The contention split
  (``pct_we`` / ``pct_other`` / ``total_busy_pct``) is derived from ``/proc/stat`` sampled
  at window start and end vs. ``RUSAGE_CHILDREN`` CPU-seconds, so an uncontended run (we
  had the box) is distinguishable from a contended one (other work ate the cores).
* :func:`append_step_profiles` appends per-step measurement rows to a
  machine/container-specific CSV. The header is the standard :data:`STEP_PROFILE_COLUMNS`
  (run context plus the scheduler's per-step keys) widened with any dynamic per-row keys
  (e.g. ``cpu.*`` counters); it widens across runs without ever dropping a column.
* :class:`CsvMetricsSink` is a concrete file-backed implementation of the
  :class:`~safe_ci_dag_runner.protocols.MetricsSink` protocol wiring the two together.

Key generalization over the DeepScry original: the DeepScry code GUESSES the output
directory by walking two levels up from the project checkout (``<parent>/validate_perf/``)
and only writes when that opt-in directory already exists. That heuristic is a
DeepScry-harness-layout specific and is removed here. The output directory is an EXPLICIT
constructor / function argument; the caller decides where the data lives. The directory is
created on demand (``mkdir(parents=True)``); a failure to create or write it is surfaced as
a visible warning and returns ``None`` (No Silent Failure) rather than being swallowed.

Two further DeepScry specifics dropped: the whole-run ``machine_id().csv`` layout and the
row context read from DeepScry-named environment variables (``VALIDATE_PROFILE_BASE_SHA``,
``VALIDATE_CPU_ENFORCEMENT_KIND``, ``RUNNER_NAME``) are replaced by plain constructor
arguments with neutral defaults.

Linux cgroup-v2 only for :func:`container_class` (matches the DeepScry target).
"""

from __future__ import annotations

import csv
import fcntl
import os
import re
import resource
import sys
import time
from collections.abc import Mapping, Sequence
from pathlib import Path

from safe_ci_dag_runner.protocols import MetricsSink, RunWindow

__all__ = [
    "CSV_COLUMNS",
    "STEP_PROFILE_COLUMNS",
    "ENRICHMENT_COLUMNS",
    "machine_id",
    "nproc",
    "container_class",
    "store_paths",
    "append_step_profiles",
    "PerfWindow",
    "CsvMetricsSink",
]

#: CSV row terminator. The stdlib csv module defaults to RFC-4180 ``\r\n`` (CRLF); we pin ``\n``
#: (LF) so the on-disk store is byte-identical to the Rust build (which writes LF) and a checked-in
#: store does not churn every line when regenerated by the other build.
_CSV_LINETERMINATOR = "\n"

# ---------------------------------------------------------------------------
# On-disk schemas. Append-only: never reorder or remove a column (old rows would
# misalign); only append new columns at the end.
# ---------------------------------------------------------------------------

#: Whole-run summary columns, one row per run.
CSV_COLUMNS = [
    "timestamp",       # ISO-8601 local time the run finished
    "machine_id",      # CPU model, run-benchmark-style (spaces->_, non-alnum stripped)
    "git_sha",         # source revision at run time
    "nproc",           # cores the run could use (len(sched_getaffinity))
    "wall_s",          # wall-clock seconds of the run window
    "user_s",          # delta RUSAGE_CHILDREN user CPU-seconds
    "sys_s",           # delta RUSAGE_CHILDREN system CPU-seconds
    "result",          # run outcome verbatim (e.g. "pass" | "fail")
    "n_steps",         # number of steps run
    "pct_we",          # our (user+sys) CPU / (nproc*wall)
    "pct_other",       # other-activity CPU / (nproc*wall)
    "total_busy_pct",  # total system busy CPU / (nproc*wall)
    "ipc",             # optional instructions-per-cycle (blank when unavailable)
    "cache_miss_pct",  # optional cache-miss rate % (blank when unavailable)
    "jobs",            # effective scheduler fan-out (-j)
]

#: Standard per-step profile columns, keyed by ``machine_id`` + ``container_class``. These
#: match exactly what the scheduler emits: the run context stamped by
#: :func:`append_step_profiles`, followed by the per-step measurement keys the scheduler
#: builds in ``scheduler._run_step`` (its ``row`` dict). Dynamic ``cpu.*`` counters vary by
#: cgroup manager and are appended per run AFTER these standard columns (see
#: :func:`_step_profile_fieldnames`), so they are captured without being hard-coded here.
#: Rich parallel-speedup enrichment columns, appended to STEP_PROFILE_COLUMNS. Captured UNDER
#: cgroup boxing on Linux and left BLANK when unavailable (an un-boxed run / missing /proc file),
#: exactly like DeepScry's writer. The NAMES mirror DeepScry's ``validate_perflog``
#: STEP_PROFILE_COLUMNS so a later schema unification is a rename, not a redesign. Produced by
#: :func:`safe_ci_dag_runner.profile_enrich.step_enrichment_columns`.
ENRICHMENT_COLUMNS = [
    "effective_cores",         # child CPU-seconds / wall (cpu.stat usage_usec / elapsed_s)
    "user_s",                  # cpu.stat user_usec, seconds
    "sys_s",                   # cpu.stat system_usec, seconds
    "throttled_s",             # cpu.stat throttled_usec, seconds
    "quota_utilization_pct",   # effective_cores / applied inner -j cap, percent
    "external_cpu_s",          # host CPU burned by OTHER tenants during the window, seconds
    "external_cores",          # ...expressed as cores
    "co_tenants_start", "co_tenants_end",
    "ambient_bucket",          # quiet | moderate | busy
    "load1_start", "load1_end", "load5_start", "load5_end",
    "host_cpu_psi_avg10_start", "host_cpu_psi_avg10_end",
    "host_cpu_psi_avg60_start", "host_cpu_psi_avg60_end",
    "host_memory_psi_avg10_start", "host_memory_psi_avg10_end",
    "host_memory_psi_avg60_start", "host_memory_psi_avg60_end",
    "host_io_psi_avg10_start", "host_io_psi_avg10_end",
    "host_io_psi_avg60_start", "host_io_psi_avg60_end",
    "step_cpu_psi_avg10_start", "step_cpu_psi_avg10_end",
    "step_cpu_psi_avg60_start", "step_cpu_psi_avg60_end",
]

STEP_PROFILE_COLUMNS = [
    # Run context, stamped onto every row by append_step_profiles().
    "timestamp", "machine_id", "container_class", "git_sha", "outer_jobs",
    "profile_base_sha", "enforcement_kind", "runner_name",
    # Per-step measurements produced by the scheduler.
    "step", "classification", "inner_jobs", "elapsed_s", "returncode", "ok",
    "timed_out", "cpu_timed_out", "oom_kills", "peak_bytes", "thread_peak",
    # Rich parallel-speedup enrichment (appended; blank when unavailable).
    *ENRICHMENT_COLUMNS,
]


# ---------------------------------------------------------------------------
# Machine / container identity + system-wide CPU sampling.
# ---------------------------------------------------------------------------


def machine_id() -> str:
    """Per-machine identifier from ``/proc/cpuinfo`` 'model name' (spaces -> underscores,
    then non ``[A-Za-z0-9_-]`` stripped). Falls back to the hostname, then ``"unknown"``.
    Mirrors run_benchmark-style CPU naming so rows group cleanly per machine."""
    try:
        with open("/proc/cpuinfo") as f:
            for line in f:
                if line.startswith("model name"):
                    name = line.split(":", 1)[1].strip().replace(" ", "_")
                    return re.sub(r"[^A-Za-z0-9_-]", "", name)
    except OSError:
        pass
    return re.sub(r"[^A-Za-z0-9_-]", "", os.uname().nodename) or "unknown"


def nproc() -> int:
    """Cores this run could actually use (respects CPU affinity / cgroup pin)."""
    try:
        return len(os.sched_getaffinity(0))
    except (AttributeError, OSError):
        return os.cpu_count() or 1


def container_class() -> str:
    """Stable CPU-container key: affinity width plus the cgroup-v2 CPU quota
    (``/sys/fs/cgroup/cpu.max``). cgroup-v2 only, matching the target host."""
    quota = "unknown"
    try:
        quota = Path("/sys/fs/cgroup/cpu.max").read_text().strip().replace(" ", "_")
    except OSError:
        pass
    return f"affinity{nproc()}_cpu-max-{quota}"


def _whole_run_csv_name(machine_id_value: str | None = None) -> str:
    """The whole-run summary CSV file name for a machine: ``<machine_id>.csv``."""
    mid = machine_id() if machine_id_value is None else machine_id_value
    return f"{mid}.csv"


def _step_profiles_csv_name() -> str:
    """The per-step profile CSV file name:
    ``step_profiles_<machine_id>_<container_class>.csv``."""
    return f"step_profiles_{machine_id()}_{container_class()}.csv"


def store_paths(output_dir: str | Path) -> list[Path]:
    """The profile-store file paths a single ``run``/``sweep`` writes into ``output_dir``: the
    whole-run summary (``<machine_id>.csv``) and the per-step profile CSV
    (``step_profiles_<machine_id>_<container_class>.csv``).

    The CLI reports EXACTLY these (filtered to files that exist) rather than globbing the whole
    store — a persistent store also holds prior runs' other-``container_class`` variants on the same
    machine, and globbing would over-report files this run never wrote."""
    base = Path(output_dir)
    return [base / _whole_run_csv_name(), base / _step_profiles_csv_name()]


def _proc_stat_busy_jiffies() -> int | None:
    """Sum of all non-idle jiffies from the aggregate 'cpu ' line of ``/proc/stat``.
    Busy = everything except idle + iowait (iowait is not CPU-burning work). ``None`` when
    ``/proc/stat`` is unreadable or malformed."""
    try:
        with open("/proc/stat") as f:
            first = f.readline()
    except OSError:
        return None
    parts = first.split()
    if not parts or parts[0] != "cpu":
        return None
    vals = [int(x) for x in parts[1:]]
    idle = vals[3] if len(vals) > 3 else 0      # idle jiffies
    iowait = vals[4] if len(vals) > 4 else 0    # iowait jiffies (when present)
    return sum(vals) - idle - iowait


# ---------------------------------------------------------------------------
# CSV append helpers (self-migrating schemas).
# ---------------------------------------------------------------------------


def _ensure_dir(output_dir: str | Path) -> Path | None:
    """Create ``output_dir`` on demand and return it, or warn + return ``None`` on failure.

    Unlike the DeepScry original (which required a pre-existing opt-in directory two levels
    up from the checkout), the directory is explicit and created eagerly; an inability to
    create it is a visible warning, never a silent skip."""
    path = Path(output_dir)
    try:
        path.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        sys.stderr.write(f"[perflog] skipped: cannot create output dir {path} ({exc})\n")
        return None
    return path


def append_step_profiles(
    output_dir: str | Path,
    rows: Sequence[Mapping[str, object]],
    *,
    git_sha: str,
    outer_jobs: int,
    profile_base_sha: str | None = None,
    enforcement_kind: str = "unverified",
    runner_name: str = "local",
) -> Path | None:
    """Append per-step measurement ``rows`` to a machine/container-specific CSV.

    The file is ``<output_dir>/step_profiles_<machine_id>_<container_class>.csv``. Each row
    is a heterogeneous column->value mapping owned by the caller (the scheduler's per-step
    ``row``); the shared run context (timestamp, machine id, container class, git SHA, outer
    job count, and the provenance columns) is stamped onto every row here. Writes are
    serialized with an ``flock`` sidecar so concurrent runs on one machine do not interleave;
    the sidecar is unlinked while the lock is still held, so a normal run leaves no stray
    ``*.csv.lock`` file behind without weakening the write serialization.

    The header is derived from the ACTUAL row keys: the standard columns
    (:data:`STEP_PROFILE_COLUMNS`) come first, then any extra per-row keys (dynamic ``cpu.*``
    counters) are appended in first-seen order, so no real data is ever dropped. If an
    existing file has a narrower header it is widened in place (older rows keep their columns)
    before appending. The file is created on first write. Returns the CSV path, or ``None``
    if the output directory could not be created (a visible warning is emitted).

    ``profile_base_sha`` defaults to ``git_sha``. ``enforcement_kind`` / ``runner_name``
    are recorded verbatim (neutral defaults replace the DeepScry env-var reads)."""
    logs_dir = _ensure_dir(output_dir)
    if logs_dir is None:
        return None
    path = logs_dir / _step_profiles_csv_name()
    lock_path = path.with_suffix(path.suffix + ".lock")
    common: dict[str, object] = {
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "machine_id": machine_id(),
        "container_class": container_class(),
        "git_sha": git_sha,
        "outer_jobs": outer_jobs,
        "profile_base_sha": git_sha if profile_base_sha is None else profile_base_sha,
        "enforcement_kind": enforcement_kind,
        "runner_name": runner_name,
    }
    full_rows = [{**common, **row} for row in rows]
    fieldnames = _step_profile_fieldnames(full_rows)
    with open(lock_path, "w") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        _append_rows_merging_header(path, full_rows, fieldnames)
        # Remove the 0-byte flock sidecar so a normal run leaves no stray *.csv.lock in the
        # user's --perf-dir. Unlinking AFTER the write but BEFORE releasing keeps write
        # serialization intact: a waiter that already opened this same lock inode still blocks
        # on us, and a racing opener that recreates the path only ever overlaps our post-write
        # teardown, never another writer's write. Best-effort (cosmetic): a failed unlink never
        # breaks logging.
        try:
            lock_path.unlink()
        except OSError:
            pass
    return path


def _step_profile_fieldnames(rows: Sequence[Mapping[str, object]]) -> list[str]:
    """Per-step CSV column order: the standard columns (:data:`STEP_PROFILE_COLUMNS`) first, then
    any extra per-row keys (dynamic ``cpu.*`` counters) SORTED ALPHABETICALLY. Both builds sort
    this dynamic tail identically (the Rust build iterates a ``BTreeSet``), so the CSV header is
    byte-identical across languages — asserted by the cross/ differential. Always captures the
    standard keys and never drops real row data (No Silent Failure)."""
    fields = list(STEP_PROFILE_COLUMNS)
    standard = set(fields)
    extra: set[str] = set()
    for row in rows:
        for key in row:
            if key not in standard:
                extra.add(key)
    fields.extend(sorted(extra))
    return fields


def _append_rows_merging_header(
    csv_path: Path, rows: Sequence[Mapping[str, object]], fieldnames: Sequence[str]
) -> None:
    """Append ``rows`` to ``csv_path`` under a header that is the union of any pre-existing
    header and ``fieldnames`` (existing columns first, then new columns appended).

    Creates the file with ``fieldnames`` when it is absent or empty; when an existing header
    is narrower, the file is rewritten to the widened header first so older rows keep their
    columns and no column is ever dropped. Each row is projected onto the final header, so an
    extra key that somehow escaped ``fieldnames`` is stored under a column (never a raise) as
    long as it is in the header. The caller holds any needed lock.

    This is the single place first-write file creation is handled: the file is opened for
    reading ONLY when it already exists, so a brand-new CSV is created cleanly instead of
    raising ``FileNotFoundError``."""
    new = not csv_path.exists() or csv_path.stat().st_size == 0
    if new:
        header = list(fieldnames)
    else:
        with open(csv_path, newline="") as existing:
            reader = csv.DictReader(existing)
            header = list(reader.fieldnames or [])
            old_rows = list(reader)
        widened = list(header)
        for col in fieldnames:
            if col not in widened:
                widened.append(col)
        if widened != header:
            tmp = csv_path.with_suffix(csv_path.suffix + ".tmp")
            with open(tmp, "w", newline="") as out:
                writer = csv.DictWriter(out, fieldnames=widened, lineterminator=_CSV_LINETERMINATOR)
                writer.writeheader()
                for old_row in old_rows:
                    old_row.pop(None, None)  # drop csv restkey overflow
                    writer.writerow({col: old_row.get(col, "") for col in widened})
            os.replace(tmp, csv_path)
            header = widened
    with open(csv_path, "a", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=header, lineterminator=_CSV_LINETERMINATOR)
        if new:
            writer.writeheader()
        for row in rows:
            writer.writerow({col: row.get(col, "") for col in header})


def _append_whole_run_row(csv_path: Path, row: Mapping[str, object]) -> None:
    """Append one whole-run summary ``row`` to ``csv_path`` under the additive
    :data:`CSV_COLUMNS` schema, merging with any pre-existing (possibly wider) header so
    older files keep their extra columns intact. The file is created on first write."""
    _append_rows_merging_header(csv_path, [row], CSV_COLUMNS)


# ---------------------------------------------------------------------------
# Whole-run window.
# ---------------------------------------------------------------------------


class PerfWindow:
    """A started whole-run measurement bracket; :meth:`finish` appends one summary row.

    Concrete implementation of :class:`~safe_ci_dag_runner.protocols.RunWindow`. Construct
    via :meth:`start` (captures baseline wall clock, ``RUSAGE_CHILDREN`` CPU, and
    system-wide busy jiffies), then call :meth:`finish` once the DAG completes. The row is
    written to ``<output_dir>/<machine_id>.csv``. The summary row is appended regardless of
    ``result`` (both passing and failing runs are recorded)."""

    def __init__(
        self,
        *,
        output_dir: str | Path,
        git_sha: str,
        machine_id_value: str,
        wall_start: float,
        ru_start: resource.struct_rusage,
        busy_start: int | None,
        ipc: object = "",
        cache_miss_pct: object = "",
    ) -> None:
        self.output_dir = output_dir
        self.git_sha = git_sha
        self.machine_id_value = machine_id_value
        self.wall_start = wall_start
        self.ru_start = ru_start
        self.busy_start = busy_start
        self.ipc = ipc
        self.cache_miss_pct = cache_miss_pct

    @classmethod
    def start(
        cls,
        *,
        output_dir: str | Path,
        git_sha: str,
        machine_id_value: str | None = None,
        ipc: object = "",
        cache_miss_pct: object = "",
    ) -> "PerfWindow":
        """Open the window, capturing baseline counters at the current instant."""
        return cls(
            output_dir=output_dir,
            git_sha=git_sha,
            machine_id_value=machine_id() if machine_id_value is None else machine_id_value,
            wall_start=time.time(),
            ru_start=resource.getrusage(resource.RUSAGE_CHILDREN),
            busy_start=_proc_stat_busy_jiffies(),
            ipc=ipc,
            cache_miss_pct=cache_miss_pct,
        )

    def finish(self, *, result: str, n_steps: int, jobs: int) -> Mapping[str, object] | None:
        """Compute window metrics and append the summary row.

        Derives the contention split from the baseline captured at :meth:`start`:

        * ``pct_we``          = our (user+sys child CPU-seconds) / (nproc * wall)
        * ``pct_other``       = (system busy CPU-seconds - our CPU-seconds) / (nproc * wall)
        * ``total_busy_pct``  = system busy CPU-seconds / (nproc * wall)

        ``pct_other`` / ``total_busy_pct`` are blank when ``/proc/stat`` could not be
        sampled at both ends. Returns the recorded row for logging, or ``None`` when the
        output directory could not be created / written (a visible warning is emitted).
        Never raises into the run path — metrics recording must not fail a run."""
        try:
            wall = max(time.time() - self.wall_start, 0.0)
            ru_end = resource.getrusage(resource.RUSAGE_CHILDREN)
            user_s = max(ru_end.ru_utime - self.ru_start.ru_utime, 0.0)
            sys_s = max(ru_end.ru_stime - self.ru_start.ru_stime, 0.0)
            ncpu = nproc()
            capacity = ncpu * wall if wall > 0 else 0.0
            our_cpu = user_s + sys_s

            total_busy_s: float | None = None
            busy_end = _proc_stat_busy_jiffies()
            if self.busy_start is not None and busy_end is not None:
                clk = os.sysconf("SC_CLK_TCK") or 100
                total_busy_s = max(busy_end - self.busy_start, 0) / clk

            def pct(x: float) -> float | str:
                return round(100.0 * x / capacity, 2) if capacity > 0 else ""

            pct_we = pct(our_cpu)
            if total_busy_s is not None:
                pct_other: float | str = pct(max(total_busy_s - our_cpu, 0.0))
                total_busy_pct: float | str = pct(total_busy_s)
            else:
                pct_other = ""
                total_busy_pct = ""

            row: dict[str, object] = {
                "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
                "machine_id": self.machine_id_value,
                "git_sha": self.git_sha,
                "nproc": ncpu,
                "wall_s": round(wall, 1),
                "user_s": round(user_s, 1),
                "sys_s": round(sys_s, 1),
                "result": result,
                "n_steps": n_steps,
                "pct_we": pct_we,
                "pct_other": pct_other,
                "total_busy_pct": total_busy_pct,
                "ipc": self.ipc,
                "cache_miss_pct": self.cache_miss_pct,
                "jobs": jobs,
            }

            logs_dir = _ensure_dir(self.output_dir)
            if logs_dir is None:
                return None
            _append_whole_run_row(logs_dir / _whole_run_csv_name(self.machine_id_value), row)
            return row
        except Exception as exc:  # never break the run over perf logging
            try:
                sys.stderr.write(f"[perflog] whole-run row skipped ({exc})\n")
            except Exception:
                pass
            return None


# ---------------------------------------------------------------------------
# Concrete MetricsSink.
# ---------------------------------------------------------------------------


class CsvMetricsSink(MetricsSink):
    """File-backed :class:`~safe_ci_dag_runner.protocols.MetricsSink` writing CSV rows.

    Carries the fixed run context (explicit output directory, git SHA, machine id, and the
    per-step provenance columns) as construction state; the scheduler passes only the
    varying per-call data. The output directory is an EXPLICIT argument — the generalization
    over DeepScry, which guessed it from the checkout layout — and is created on demand."""

    def __init__(
        self,
        output_dir: str | Path,
        *,
        git_sha: str,
        machine_id_value: str | None = None,
        profile_base_sha: str | None = None,
        enforcement_kind: str = "unverified",
        runner_name: str = "local",
        ipc: object = "",
        cache_miss_pct: object = "",
    ) -> None:
        self.output_dir = output_dir
        self.git_sha = git_sha
        self.machine_id_value = machine_id() if machine_id_value is None else machine_id_value
        self.profile_base_sha = profile_base_sha
        self.enforcement_kind = enforcement_kind
        self.runner_name = runner_name
        self.ipc = ipc
        self.cache_miss_pct = cache_miss_pct

    def start_run_window(self) -> RunWindow:
        """Open the whole-run window bound to this sink's context."""
        return PerfWindow.start(
            output_dir=self.output_dir,
            git_sha=self.git_sha,
            machine_id_value=self.machine_id_value,
            ipc=self.ipc,
            cache_miss_pct=self.cache_miss_pct,
        )

    def record_step_profiles(
        self, rows: Sequence[Mapping[str, object]], *, jobs: int
    ) -> str | None:
        """Append per-step profile ``rows`` (accumulated during the run) to durable storage.

        Delegates to :func:`append_step_profiles`; ``jobs`` is stamped as ``outer_jobs`` on
        every row. Rows are recorded regardless of run outcome. Returns the CSV path as a
        string, or ``None`` when recording was skipped (a visible warning is emitted)."""
        path = append_step_profiles(
            self.output_dir,
            rows,
            git_sha=self.git_sha,
            outer_jobs=jobs,
            profile_base_sha=self.profile_base_sha,
            enforcement_kind=self.enforcement_kind,
            runner_name=self.runner_name,
        )
        return None if path is None else str(path)
