// GENERATED by contract/generate.mjs from contract/vibe-talk.schema.json. Do not edit;
// change src/contract.rs and run `make -C vibe-talk contract`.
//
// The vibe-talk wire contract, for TypeScript's checkJs pass over the page. The same types are
// validated at runtime by web/contract.js.

declare namespace VibeTalk {
  /**
   * A JSON error body.
   */
  interface ApiErrorBody {
    /**
     * Human-readable detail. Never contains a secret.
     */
    detail: string;
    /**
     * Stable machine-readable code.
     */
    error: string;
  }

  /**
   * A Discord channel snowflake, as a string, exactly as Discord renders it.
   */
  type ChannelId = string;

  /**
   * A channel this server is configured to read.
   */
  interface ChannelInfo {
    /**
     * Whether this channel was added from inside the app rather than named in the configuration
     * file.
     *
     * The page needs it for one decision: only an added channel can be REMOVED from the app. A
     * configured one comes from a file this server reads and never writes, so taking it out here
     * would last until the next restart and then undo itself — the server refuses that, and this
     * is what stops the app offering a button whose whole outcome is a refusal.
     */
    added: boolean;
    /**
     * The operator's own local name for this channel, when he has set one. `#39 channel-alias`.
     *
     * **Local, and only ours.** It lives in this server's store, exactly as read state does; it
     * is never sent to Discord, renames nothing there, and no one outside this deployment sees
     * it. It is set by the OPERATOR through the web app — never by the voice agent, which would
     * otherwise be renaming the things it is also reporting on.
     *
     * `None` means "no alias", which is not the same as an empty one: an empty alias is refused
     * at the door, and clearing an alias is a separate act that puts [`ChannelInfo::label`] back.
     *
     * It is `None` on a channel that came straight from [`crate::config::Config`]; the store
     * overlay in [`crate::ops`] is what fills it in, so anything reading configuration directly
     * — the startup banner, the preflight probe — still names the label the operator wrote.
     */
    alias: string | null;
    /**
     * Snowflake of the channel.
     */
    id: ChannelId;
    /**
     * Human label used in speech and in the web app ("acme lead team").
     *
     * This one comes from the operator's CONFIGURATION file and cannot be changed at runtime.
     * What a person actually hears is [`ChannelInfo::display_name`], because `#39 channel-alias`
     * lets him rename a channel from inside the app without editing a file or redeploying.
     */
    label: string;
    /**
     * Whether posting into this channel is permitted at all.
     */
    writable: boolean;
  }

  /**
   * What the web app needs to know at startup.
   */
  interface ClientConfigResponse {
    /**
     * Whether the selected provider can list its channels for browsing. `#19 channel-browser`.
     */
    channel_discovery_supported: boolean;
    /**
     * Whether the selected provider accepts channel links or references and manages registration.
     */
    channel_registration_supported: boolean;
    /**
     * Configured channels.
     */
    channels: ChannelInfo[];
    /**
     * Source chat service's human-readable name, supplied by the selected backend.
     */
    chat_provider_name: string;
    /**
     * Selected conversational voice provider, named by its implementation.
     */
    conversational_voice: VoiceDescription;
    /**
     * ElevenLabs agent id, when the deployment has one. Not a secret: it identifies a public
     * widget. The API key never leaves the server.
     */
    elevenlabs_agent_id: string | null;
    /**
     * How changes reach the SSE hub.
     */
    live_delivery: LiveDelivery;
    /**
     * Seconds between live ingestion ticks, or `0` when live ingestion is OFF.
     *
     * The page needs this to tell the truth about its own channel view. With ingestion off the
     * SSE stream attaches and delivers nothing, which is indistinguishable from a quiet channel;
     * a page that showed a "live" indicator on that basis would be claiming a freshness it does
     * not have. Not a secret: it is a property of this deployment, and the caller already holds
     * a token.
     */
    live_poll_seconds: number;
    /**
     * The READER's own Discord account, when the operator has said what it is.
     *
     * Distinct from `self_author_id`, which is the BRIDGE's account and is read out of the bot
     * token. This one cannot be derived from anything the server holds — a bot's account has no
     * relationship to the human reading the channel — so it is absent unless configured. The page
     * draws both as the owner's own words, because they are: one typed into Discord, one dictated
     * through this bridge.
     */
    owner_author_id: string | null;
    /**
     * Selected read-aloud backend and the playback interface the browser should use.
     */
    read_aloud: Description;
    /**
     * Whether the operator has allowed an earlier transcript to be replayed into a new call.
     *
     * The page needs it BEFORE it has anything to replay: the Settings screen has to describe
     * what resuming will do, and the control's own note has to say what the next call will be —
     * both of which are questions asked while there is no conversation to fetch.
     */
    replay_enabled: boolean;
    /**
     * The Discord account this bridge posts as, when it can be known.
     *
     * NOT a secret: a bot's user id is visible on every message it has ever sent. It is here so
     * the channel view can tell the owner's own words -- posted on his behalf by this bridge --
     * from everybody else's, on the FIRST render rather than only after he has replied from the
     * app. `None` when the token is not in the shape ids can be read from; the page then falls
     * back to learning it the old way.
     */
    self_author_id: string | null;
    /**
     * Whether this server rewrites message bodies for speech before anything says them.
     *
     * Here for the same reason as `replay_enabled`: Settings has to be able to describe what this
     * deployment does, and the page cannot infer this one from any message it holds. An empty
     * `spoken_content` means "the rewrite changed nothing" just as often as it means "the pass is
     * off" — deliberately, see [`crate::model::Message::spoken_content`] — so a page guessing from
     * the data would tell the operator the feature was off every time the channel was plain prose.
     * They are flipping this switch to compare two runs; guessing is exactly what they cannot do.
     */
    speech_prep_enabled: boolean;
    /**
     * Whether the backend supports channel, thread-list, and flattened timelines.
     */
    threading_supported: boolean;
    /**
     * The scope of the token that asked.
     *
     * The caller's own scope, so it discloses nothing it did not already hold. The page needs it
     * to avoid asking for what this token cannot have: stored conversations are write-only (see
     * the conversation routes), and a read-scope page that probed them anyway got a 403 and a
     * console error on every load. `#38 read-token-conversation-probe`.
     */
    token_scope: TokenScope;
    /**
     * Whether the selected provider exposes a write-through read cursor.
     */
    upstream_read_mark_supported: boolean;
    /**
     * Server version, so a stale cached page is visible.
     */
    version: string;
  }

  /**
   * A confirmed proposal, posted.
   */
  interface CommittedPostResponse {
    /**
     * Every part, in order. One element for a message that fitted.
     */
    parts: Message[];
    /**
     * The FIRST message as the chat service accepted it.
     */
    posted: Message;
    /**
     * Which proposal this was.
     */
    serial: number;
  }

  /**
   * Public capabilities of the selected read-aloud provider; never contains credentials.
   */
  interface Description {
    /**
     * Stable provider identifier.
     */
    backend: string;
    /**
     * Human-readable provider name.
     */
    label: string;
    /**
     * Whether browser speech must select a voice advertised as running locally.
     * This is the browser's `localService` flag; the device engine controls actual networking.
     */
    local_only: boolean;
    /**
     * Which playback interface the browser should use.
     */
    playback: Playback;
  }

  /**
   * The data of a live stream `message_delete` event: only the ids, never the removed text.
   */
  interface LiveDeleteEvent {
    /**
     * Channel the message was removed from.
     */
    channel_id: ChannelId;
    /**
     * Whether it was published before this stream attached; see [`LiveMessageEvent::from_tail`].
     */
    from_tail: boolean;
    /**
     * The message that was removed.
     */
    message_id: MessageId;
    /**
     * Whether it was classified as history rather than news.
     */
    replayed: boolean;
  }

  /**
   * How channel changes reach the live stream.
   */
  type LiveDelivery = "off" | "poll" | "push";

  /**
   * The data of a live stream `message` or `message_update` event.
   */
  interface LiveMessageEvent {
    /**
     * Whether it was published before this stream attached and is re-sent from the replay tail.
     * Any channel read begun after the stream's response arrived has already seen it. An
     * adapter's catch-up arriving after the attach is `replayed` but not from the tail: it may be
     * newer than every read the page has made.
     */
    from_tail: boolean;
    /**
     * The message as it now stands. UNTRUSTED: written by whoever is in the channel.
     */
    message: Message;
    /**
     * Whether it was classified as history — a replay or a catch-up — rather than news. The page
     * may render such a message but must not announce it to a live conversation.
     */
    replayed: boolean;
    /**
     * Whether THIS SERVER posted it; the page must not relay these into a live conversation.
     */
    self_posted: boolean;
    /**
     * Standing reminder that the content is third-party text.
     */
    untrusted_content_notice: string;
  }

  /**
   * The data of a live stream `reset` event: the subscriber fell behind the replay tail.
   */
  interface LiveResetEvent {
    /**
     * What the subscriber should do instead of resuming.
     */
    detail: string;
    /**
     * Events this subscriber missed, or `0` when the count is unknown.
     */
    missed: number;
  }

  /**
   * One chat message as the rest of the server sees it.
   */
  interface Message {
    /**
     * Display name of the author, as reported by the chat provider.
     */
    author: string;
    /**
     * Snowflake of the author.
     *
     * This travels with every rendered message ON PURPOSE, and the alternative — a
     * "look up this display name" tool — was rejected. Two reasons, in order of importance:
     *
     * 1. **No lookup step, so nothing to guess.** The id arrives ATTACHED to the very message
     *    being replied to, so a caller that wants to mention its author already holds the exact
     *    snowflake. A lookup tool would put a fuzzy name match between the agent and a real
     *    notification, and a hallucinated id pings a stranger.
     * 2. **It bounds who can be mentioned.** The only ids a caller ever sees are those of people
     *    and bots that have actually spoken in an allowlisted channel. A general user-lookup tool
     *    would let the agent ping anyone in the server, which is a strictly larger capability
     *    than this project wants to hand a voice model.
     *
     * Bots have ids too and they are included: addressing another coding agent by mention is a
     * legitimate thing to want.
     */
    author_id: UserId;
    /**
     * Whether the chat provider flagged the author as a bot.
     */
    author_is_bot: boolean;
    /**
     * Channel the message was read from, in the provider-neutral application namespace.
     */
    channel_id: ChannelId;
    /**
     * Raw message body. UNTRUSTED: written by whoever is in the channel.
     */
    content: string;
    /**
     * Snowflake of this message.
     */
    id: MessageId;
    /**
     * The message this one is a reply to, when it is one.
     *
     * Discord records a reply on the REPLYING message, as `message_reference.message_id`, and
     * nowhere else — there is no "replies" field on the message being answered. So "has this been
     * replied to?" is not a fact a single message carries; it is derived by looking at what else
     * is loaded. That derivation belongs to the reader, which is why this field is the raw pointer
     * and not a `has_replies` boolean:
     *
     * 1. **A boolean computed here would be a lie about scope.** The server answers a read with a
     *    WINDOW of a channel, so it could only ever mean "replied to within this window", and a
     *    field named `has_replies` would be believed to mean more than that.
     * 2. **The pointer is the durable fact.** It is true of the message forever, independently of
     *    what else happens to be loaded beside it.
     *
     * `None` for an ordinary message, and also for a reply whose reference Discord did not
     * include. Absent is not "not a reply"; it is "no pointer was reported", and nothing should
     * present the two differently.
     */
    reply_to: MessageId | null;
    /**
     * The same body rewritten for speech by [`crate::speakable`]: markdown off, instants said the
     * way a listener places them, long ids and hashes named. READ THIS ONE ALOUD.
     *
     * Two fields for the same reason there are two time fields — they answer different questions.
     * `content` is what was written and is what the SCREEN must show, character for character;
     * this is what a voice should say, and saying it costs the reader none of the seconds that
     * spelling a nineteen-digit snowflake costs. Neither is a substitute for the other, and a
     * renderer that picked one for both jobs would be wrong in one of them.
     *
     * UNTRUSTED, exactly as much as `content` is: rewriting a body for speech is not sanitizing it
     * for a prompt, and it still goes through [`crate::untrusted`] on the way to a model.
     *
     * EMPTY means "the body to say is the raw body". That covers two cases on purpose: nothing has
     * prepared this message yet — the chat adapters hold no configuration, so [`crate::ops`] is the
     * only filler, the same convention as [`Message::spoken_time`] — and the prepared form came
     * back identical, which is the common case for ordinary chat with no markdown and no ids in
     * it. One value can mean both because [`Message::spoken_body`] answers them the same way, and
     * collapsing them is what keeps a window of a hundred messages from carrying a hundred
     * near-copies of itself down a phone's connection. When the field IS set, something was
     * genuinely rewritten.
     */
    spoken_content?: string;
    /**
     * The same instant in the operator's configured zone, already formatted for speech: `09:51`.
     * READ THIS ONE ALOUD.
     *
     * Two fields rather than one because they answer different questions, and because a single
     * field would force whoever renders it to choose — which is exactly the choice that produced
     * the bug. Handed an ISO string in UTC, the assistant said "thirteen fifty-one Eastern Time":
     * it kept the digits and relabelled them. A value that is already correct when read verbatim
     * requires no conversion and admits no such mistake.
     *
     * No seconds and no zone label: see [`crate::clock::spoken`], which explains what carrying
     * them cost a listener and what dropping them trades away.
     *
     * EMPTY means "not yet stamped". The Discord layer constructs it empty because it holds no
     * configuration and therefore does not know the operator's zone; [`crate::ops`] is the only
     * filler. Use [`Message::spoken`] to read it, which falls back to the exact instant rather
     * than to a blank.
     */
    spoken_time: string;
    /**
     * Thread membership supplied by the backend; independent of a reply-to message reference.
     */
    thread?: MessageThread | null;
    /**
     * The exact instant, ISO-8601, as reported by the chat provider. Compute with this one.
     *
     * Unrounded on purpose: sub-second precision is ordering information, and anything that has
     * to decide which of two messages came first needs it. This field is never spoken; see
     * [`Message::spoken_time`] for the one that is.
     */
    timestamp: string;
  }

  /**
   * A Discord message snowflake, as a string.
   */
  type MessageId = string;

  /**
   * Thread membership attached to a message without conflating it with a reply reference.
   */
  interface MessageThread {
    /**
     * Opaque thread identifier, scoped to the configured channel.
     */
    id: string;
    /**
     * Whether this message is the original thread root.
     */
    is_root: boolean;
    /**
     * Number of replies, when the provider can supply it.
     */
    reply_count: number | null;
    /**
     * Whether the reply count is exact rather than a provider estimate.
     */
    reply_count_exact: boolean;
    /**
     * The original channel message, if this provider exposes one.
     */
    root_message_id: MessageId | null;
  }

  /**
   * A post waiting for the owner's confirmation. `#34 voice-chat-write-confirm`.
   *
   * Everything the confirmation has to show — the exact text, where it goes, what it answers — and
   * the handle that commits exactly this. The handle is a capability: it is handed only to a
   * write-scope caller of the proposal routes, never to a model, and a commit must restate the
   * channel, text, and reply target it was issued for.
   */
  interface PendingPost {
    /**
     * The channel it would be posted to.
     */
    channel_id: ChannelId;
    /**
     * That channel's name as the owner knows it, alias included.
     */
    channel_name: string;
    /**
     * Milliseconds until the handle expires.
     */
    expires_in_ms: number;
    /**
     * The single-use confirmation handle.
     */
    handle: string;
    /**
     * The message it would reply to, when any.
     */
    reply_to: MessageId | null;
    /**
     * Correlates this proposal's steps in the access log. Increases with every proposal.
     */
    serial: number;
    /**
     * The exact text that would be posted.
     */
    text: string;
  }

  /**
   * The post waiting for confirmation, or `null` when none is.
   */
  interface PendingPostResponse {
    /**
     * The pending proposal. At most one exists: a new proposal supersedes the old.
     */
    proposal: PendingPost | null;
  }

  /**
   * How the web app plays messages with the selected provider.
   */
  type Playback = "browser" | "audio";

  /**
   * One thread in the thread list, independent of the underlying provider's channel model.
   */
  interface ThreadSummary {
    /**
     * Opaque identifier used for reading or posting to this thread.
     */
    id: string;
    /**
     * Number of replies when known.
     */
    reply_count: number | null;
    /**
     * Whether the reported count is exact.
     */
    reply_count_exact: boolean;
    /**
     * The original message, when available and readable.
     */
    root: Message | null;
    /**
     * Provider-supplied title, or a neutral fallback.
     */
    title: string;
    /**
     * Latest message activity, as an RFC 3339 timestamp.
     */
    updated_at: string;
  }

  /**
   * A provider-neutral timeline plus this application's channel and read-state metadata.
   */
  interface TimelineResponse {
    /**
     * Configured parent channel, including its local alias and write policy.
     */
    channel: ChannelInfo;
    /**
     * Messages on this page that the reader has archived locally.
     */
    dismissed: MessageId[];
    /**
     * Whether another backward page exists.
     */
    has_more: boolean;
    /**
     * Whether accessible threads exist in this channel.
     */
    has_threads: boolean;
    /**
     * Page size actually requested.
     */
    limit: number;
    /**
     * Messages for main, flat, or thread views, ordered oldest first.
     */
    messages: Message[];
    /**
     * Opaque continuation, present exactly when another page exists.
     */
    next_before: string | null;
    /**
     * Relevant provider limitation or scope information, if any.
     */
    notice: string | null;
    /**
     * Entries on this page, never a channel-wide total.
     */
    returned: number;
    /**
     * The selected thread, for the thread view. Outside it, the one thread a channel registered as
     * a single conversation is scoped to: that channel has no child threads (`has_threads` is
     * false), and its main view carries the conversation's replies as well as its root.
     */
    thread: ThreadSummary | null;
    /**
     * Summaries for the threads view, ordered by last activity oldest first.
     */
    threads: ThreadSummary[];
    /**
     * Channel content remains untrusted data in every view.
     */
    untrusted_content_notice: string;
    /**
     * View represented by this page.
     */
    view: TimelineView;
  }

  /**
   * A view of one configured channel.
   */
  type TimelineView = "main" | "threads" | "flat" | "thread";

  /**
   * The scope of the credential that made a request.
   */
  type TokenScope = "read" | "write";

  /**
   * Who spoke a `vibe-talk-v1` transcript line.
   */
  type TranscriptRole = "user" | "assistant";

  /**
   * A Discord user snowflake, as a string.
   *
   * Kept distinct from [`MessageId`] and [`ChannelId`] so the three cannot be passed for one
   * another: they are all decimal snowflakes, and a wrong one is silently plausible.
   */
  type UserId = string;

  /**
   * A JSON control frame a `vibe-talk-v1` client sends. Microphone audio travels separately, as
   * binary PCM at the session's input rate.
   */
  type VibeTalkV1ClientFrame = {
    type: "audio_start";
  } | {
    type: "audio_end";
  } | {
    /**
     * What the person typed.
     */
    text: string;
    type: "prompt";
  } | {
    type: "interrupt";
  } | {
    type: "quit";
  };

  /**
   * A JSON control frame a `vibe-talk-v1` server sends. Audio travels separately, as binary frames
   * of 24 kHz, 16-bit little-endian mono PCM.
   *
   * A client ignores a `type` it does not know, so a new frame type is backward compatible; a
   * changed field of a known type is not.
   */
  type VibeTalkV1ServerFrame = {
    /**
     * Whether the agent speaks first. When true, a voice client withholds microphone frames
     * until the first `turn_complete`. Absent means false.
     */
    greeting?: boolean | null;
    /**
     * Provider session identifier, for connection details only.
     */
    session_id?: string | null;
    type: "session_started";
  } | {
    /**
     * False for a streaming hypothesis the provider may still correct. Absent means true, so
     * a provider that only sends finished text needs no change.
     */
    final?: boolean | null;
    /**
     * Who said it.
     */
    role: TranscriptRole;
    /**
     * The words, or the current hypothesis of them.
     */
    text: string;
    /**
     * The turn this text belongs to. A frame without one cannot be matched and is treated as
     * its own turn.
     */
    turn?: number | null;
    type: "transcript";
  } | {
    /**
     * True when an `interrupt` cut the turn short.
     */
    interrupted?: boolean | null;
    /**
     * The turn that ended.
     */
    turn?: number | null;
    type: "turn_complete";
  } | {
    /**
     * Additional detail, when the provider has any.
     */
    detail?: string | null;
    /**
     * What went wrong, in words.
     */
    message?: string | null;
    type: "error";
  };

  /**
   * Stable provider details that can be shown before a session is opened.
   */
  interface VoiceDescription {
    /**
     * Provider instance identifier, when one exists.
     */
    instance_id?: string | null;
    /**
     * Human-readable provider name.
     */
    name: string;
    /**
     * Provider console for the configured agent, when one exists.
     */
    settings_url?: string | null;
  }

  /**
   * A browser-ready conversational voice session.
   */
  interface VoiceSession {
    /**
     * Microphone PCM sample rate expected by the provider.
     */
    input_sample_rate: number;
    /**
     * Speaker PCM sample rate emitted by the provider.
     */
    output_sample_rate: number;
    /**
     * Wire protocol spoken on the socket.
     */
    protocol: string;
    /**
     * Human-readable provider label for connection details.
     */
    provider: string;
    /**
     * Endpoint validity when the provider issues expiring URLs.
     */
    valid_for_seconds?: number | null;
    /**
     * WebSocket endpoint for this conversation.
     */
    websocket_url: string;
  }

  /** Every type that crosses a boundary on its own, by name. */
  interface Contract {
    ApiErrorBody: ApiErrorBody;
    ClientConfigResponse: ClientConfigResponse;
    VoiceSession: VoiceSession;
    TimelineResponse: TimelineResponse;
    PendingPostResponse: PendingPostResponse;
    CommittedPostResponse: CommittedPostResponse;
    LiveMessageEvent: LiveMessageEvent;
    LiveDeleteEvent: LiveDeleteEvent;
    LiveResetEvent: LiveResetEvent;
    VibeTalkV1ServerFrame: VibeTalkV1ServerFrame;
    VibeTalkV1ClientFrame: VibeTalkV1ClientFrame;
    Message: Message;
    ThreadSummary: ThreadSummary;
  }

  /** A contract type a peer may extend with new `type` tags. */
  type Tagged = "VibeTalkV1ServerFrame";

  /** The error {@link VibeTalkContract.decode} throws. */
  interface ContractError extends Error {
    contract: keyof Contract;
  }
}

/** Runtime validators for {@link VibeTalk.Contract}, defined by web/contract.js. */
declare const VibeTalkContract: {
  /** Every root type name. */
  readonly roots: ReadonlyArray<keyof VibeTalk.Contract>;
  /** Whether value is a well-formed name. */
  is<K extends keyof VibeTalk.Contract>(name: K, value: unknown): value is VibeTalk.Contract[K];
  /** value, if well formed; otherwise throws a {@link VibeTalk.ContractError}. */
  decode<K extends keyof VibeTalk.Contract>(name: K, value: unknown): VibeTalk.Contract[K];
  /**
   * null when value carries a `type` tag this contract does not know, which a receiver ignores;
   * otherwise as {@link decode}.
   */
  decodeTagged<K extends VibeTalk.Tagged>(name: K, value: unknown): VibeTalk.Contract[K] | null;
};
